
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'neuroedge-go'
    metrics_path: /metrics
    static_configs:
      - targets: ['go-backend:9000']
  - job_name: 'neuroedge-frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:3000']
