
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
  - job_name: 'qdrant'
    metrics_path: /metrics
    static_configs:
      - targets: ['qdrant:6333']
